name: Build NRD SDK
on: workflow_dispatch
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      -
        name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install windows-sdk-10.0 cmake -y
      -
        name: Install Vulkan
        run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Vulkan SDK version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install
      -
        name: Deploy NRD SDK
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\1-Deploy.bat
      -
        name: Build NRD SDK
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\2-Build.bat
      -
        name: Prepare NRD SDK
        run: |
          &'.\3-Prepare NRD SDK.bat' --shaders
      -
        name: Upload NRD SDK as artefact
        uses: actions/upload-artifact@v3
        with:
          name: NRD SDK
          path: _NRD_SDK
          
  Build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      -
        name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      -
        name: CMake Generate
        run: |
          mkdir "build"
          cd "build"
          cmake -G Ninja .. 
          cd ..
      -
        name: Build Debug
        run: |
          cd "build"
          cmake --build . --config Debug
          cd ..
      -
        name: Build Release
        run: |
          cd "build"
          cmake --build . --config Release
          cd ..
      -
         name: Test Release
         run: |
           cd "build"
           cd "bin"
           ./tests
